//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NMEntities : DbContext
    {
        public NMEntities()
            : base("name=NMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<DownloadNotes> DownloadNotes { get; set; }
        public virtual DbSet<NoteCategories> NoteCategories { get; set; }
        public virtual DbSet<NoteDetails> NoteDetails { get; set; }
        public virtual DbSet<NoteReviews> NoteReviews { get; set; }
        public virtual DbSet<NoteStatus> NoteStatus { get; set; }
        public virtual DbSet<NoteType> NoteType { get; set; }
        public virtual DbSet<SellerNoteAttachment> SellerNoteAttachment { get; set; }
        public virtual DbSet<SpamReports> SpamReports { get; set; }
        public virtual DbSet<SystemConfigurations> SystemConfigurations { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
